; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.partitions = huge_app.csv
build_flags =
    -Iinclude
    -Ilib/ModestIoT
    -Ilib/uflex/include
lib_deps =
    h2zero/NimBLE-Arduino@^2.5.0

[env:esp32_hw]
build_flags =
    ${env.build_flags}
    -D UFLEX_TARGET_HW
    '-DUFLEX_WIFI_SSID="${sysenv.UFLEX_WIFI_SSID}"'
    '-DUFLEX_WIFI_PASSWORD="${sysenv.UFLEX_WIFI_PASSWORD}"'
    '-DUFLEX_EDGE_HOST="${sysenv.UFLEX_EDGE_HOST}"'
    '-DUFLEX_DEVICE_API_KEY="${sysenv.UFLEX_DEVICE_API_KEY}"'

[env:esp32_sim]
build_flags =
    ${env.build_flags}
    -D UFLEX_TARGET_SIM
